### ISSUE TITLE
Invalid memory address exception

### ISSUE THREAD

**Issue by ryan-dyer-sp** [transcend-io/terragrunt-atlantis-config#66]
just downloaded latest master build in order to test new functionality as discussed in issue #60 .  I am now getting a runtime panic

```
> terragrunt-atlantis-config generate --autoplan --create-workspace --create-project-name --output autogen.yaml --workflow terragrunt --ignore-parent-terragrunt
[terragrunt] 2020/09/29 15:45:15 Running command: bash -c dirname $(dirname /home/user/repos/terragrunt/providers/accounts/delivery) | tr -d '
'
[terragrunt] 2020/09/29 15:45:15 Command output will be suppressed.
[terragrunt] 2020/09/29 15:45:15 run_cmd output: [REDACTED]
[terragrunt] 2020/09/29 15:45:15 Running command: bash -c echo -n /home/user/repos/terragrunt/providers/accounts/delivery/aws-limit-monitor | sed 's|/home/user/repos/terragrunt/providers||g'
[terragrunt] 2020/09/29 15:45:15 Command output will be suppressed.
[terragrunt] 2020/09/29 15:45:15 run_cmd output: [REDACTED]
[terragrunt] 2020/09/29 15:45:15 Running command: bash -c dirname $(dirname /home/user/repos/terragrunt/providers/accounts/delivery) | tr -d '
'
[terragrunt] 2020/09/29 15:45:15 Command output will be suppressed.
[terragrunt] 2020/09/29 15:45:15 run_cmd output: [REDACTED]
[terragrunt] 2020/09/29 15:45:15 Running command: bash -c echo -n /home/user/repos/terragrunt/providers/accounts/delivery | sed 's|/home/user/repos/terragrunt/providers||g'
[terragrunt] 2020/09/29 15:45:15 Command output will be suppressed.
[terragrunt] 2020/09/29 15:45:15 run_cmd output: [REDACTED]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x113d2ff]

goroutine 19 [running]:
github.com/transcend-io/terragrunt-atlantis-config/cmd.getDependencies(0xc0003545a0, 0x59, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/user/go/pkg/mod/github.com/transcend-io/terragrunt-atlantis-config@v0.9.2/cmd/generate.go:157 +0x41f
github.com/transcend-io/terragrunt-atlantis-config/cmd.createProject(0xc0003545a0, 0x59, 0x0, 0x0, 0x0)
        /home/user/go/pkg/mod/github.com/transcend-io/terragrunt-atlantis-config@v0.9.2/cmd/generate.go:171 +0x50
github.com/transcend-io/terragrunt-atlantis-config/cmd.main.func1(0x0, 0x0)
        /home/user/go/pkg/mod/github.com/transcend-io/terragrunt-atlantis-config@v0.9.2/cmd/generate.go:286 +0x7f
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc00032c2d0, 0xc00032d410)
        /home/user/go/pkg/mod/golang.org/x/sync@v0.0.0-20200625203802-6e8e738ad208/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
        /home/user/go/pkg/mod/golang.org/x/sync@v0.0.0-20200625203802-6e8e738ad208/errgroup/errgroup.go:54 +0x66
```

Let me know what other info I can provide for troubleshooting.  Thanks!

**Comment by dmattia** [comment]
That looks like it's in the `extra_arguments` field parsing step. Here is the only test file I am currently using to test that part of the code: https://github.com/transcend-io/terragrunt-atlantis-config/blob/master/test_examples/extra_arguments/child/terragrunt.hcl

My quick guess would be that this error would come up if your `extra_arguments` block did not include a `required_var_files` subfield. Does the module in question have a block with only optional var files?

I can add some extra tests for this and it should be pretty easy to figure out, but if you can confirm that question for me it would be appreciated

**Comment by dmattia** [comment]
I can confirm that when I added a test without `required_var_files`, I saw a similar error to the one you have here.

v0.9.3 has the fix in it if you wouldn't mind trying out the upgraded version: https://github.com/transcend-io/terragrunt-atlantis-config/releases/tag/v0.9.3

The PR that fixed it is here: https://github.com/transcend-io/terragrunt-atlantis-config/pull/67
It is mostly just a bunch of new test files, with two lines of application code changes

**Comment by dmattia** [comment]
Please re-open if this issue hangs around 😄
